POST https://lab3-function.azurewebsites.net/api/PersonFunction?code=Gu-XqqerArJPWiamHb5EFKyTzonI8TgSY0PzWB833aJZAzFubT6lHw== HTTP/1.1
content-type: application/json

{
    "firstName": "Mine",
    "lastName": "Guy"
}


GET https://lab3-function.azurewebsites.net/api/PersonFunction?code=Gu-XqqerArJPWiamHb5EFKyTzonI8TgSY0PzWB833aJZAzFubT6lHw== HTTP/1.1
content-type: application/json

{}


DELETE https://lab3-function.azurewebsites.net/api/PersonFunction?code=Gu-XqqerArJPWiamHb5EFKyTzonI8TgSY0PzWB833aJZAzFubT6lHw== HTTP/1.1
content-type: application/json

{
    "id": 2
}

PUT https://lab3-function.azurewebsites.net/api/PersonFunction?code=Gu-XqqerArJPWiamHb5EFKyTzonI8TgSY0PzWB833aJZAzFubT6lHw== HTTP/1.1
content-type: application/json

{
    "id": 1,
    "firstName": "Cool",
    "lastName": "Man"
}
